package lab06;

import java.io.FileInputStream;
import java.security.KeyStore;
import java.security.PrivateKey;
import java.security.cert.X509Certificate;

/*
 * Demonstrates how to read Java KeyStore from file (generated by keytool)
 * and access some of KeyStore elements.
 */
public class ReadKeyStoreDemo {
	public static void main(String[] args) throws Exception {
		// Password to access keystore
		char[] keyStorePassword = "MyKeyStorePassword".toCharArray();
		// Password to access private key
		char[] keyPassword = "MyKeyPassword".toCharArray();

		FileInputStream in = new FileInputStream(args[0]);

		// Load keystore
		KeyStore keyStore = KeyStore.getInstance("JKS");
		keyStore.load(in, keyStorePassword);

		// Get certificate
		// Here it is assumed that certificate was created with an alias 'MyAlias'.
		X509Certificate certificate = (X509Certificate) keyStore.getCertificate("MyAlias");
		System.out.println(certificate);

		// Get private key
		// Here it is assumed that certificate was created with an alias 'MyAlias'.
		PrivateKey privateKey = (PrivateKey) keyStore.getKey("MyAlias", keyPassword);
		System.out.println(privateKey);	
	}
}
